# -*- coding: utf-8 -*-
# Part of ERP Heritage Shopify Connector. See LICENSE file for full copyright and licensing details.
from . import eh_shopify_credential
from . import eh_shopify_store
from . import eh_shopify_job
from . import eh_shopify_event
from . import eh_shopify_location
from . import eh_shopify_webhook
from . import res_partner
from . import eh_shopify_customer
from . import eh_shopify_variant
from . import eh_shopify_mapping
from . import eh_shopify_order
from . import eh_shopify_store_orders
from . import eh_shopify_order_import
from . import sale_order
from . import eh_shopify_order_sale
from . import eh_shopify_fulfillment
from . import stock_picking
from . import eh_shopify_order_fulfillment
from . import eh_shopify_inventory
from . import eh_shopify_fulfillment_import
from . import eh_shopify_order_cancel
from . import eh_shopify_fulfillment_tracking
from . import eh_shopify_pickup
from . import eh_shopify_product
from . import eh_shopify_store_catalogue
from . import eh_shopify_product_create
from . import eh_shopify_bulk
from . import eh_shopify_product_sync
from . import eh_shopify_product_publish
from . import eh_shopify_product_media
from . import eh_shopify_match
from . import eh_shopify_payout
from . import eh_shopify_dispute
from . import eh_shopify_gift_card
from . import eh_shopify_history
from . import eh_shopify_metafield
from . import eh_shopify_price_list
from . import eh_shopify_customer_sync
from . import eh_shopify_metafield_parties
from . import eh_shopify_refund
from . import eh_shopify_refund_push
from . import eh_shopify_return
from . import eh_shopify_order_edit_push
